name: Renovate Auto Approve
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'trap-renovate[bot]' }}
    steps:
      - name: Approve Renovate PRs
        run: |
          gh pr review --approve ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
